export interface SearchRequest {
  oKind: string,
  dKind: string,
  currencyCode: string,
  languageCode: string,
  data: string,
  noAir: boolean,
  noAirLeg: boolean,
  noRail: boolean,
  noBus: boolean,
  noFerry: boolean,
  noCar: boolean,
  noBikeshare: boolean,
  noRideshare: boolean,
  noTowncar: boolean,
  noCommuter: boolean,
  noSpecial: boolean,
  noMinorStart: boolean,
  noMinorEnd: boolean,
  noPath: boolean,
  noPrice: boolean,
  noStop: boolean,
}
